#!/bin/sh
set -e
. "$(dirname "$0")/_/husky.sh"

echo "🌳 This is a Trunk-Based Development branch."
echo "🔒 Therefore, tests, linting, and build must pass before pushing."
echo

echo "======== Starting Tests 🧪  ========"
if bun test; then
    echo "======== Tests Completed Successfully ✅  ========"
else
    echo "❌ Tests Failed"
    exit 1
fi

echo
echo "======== Starting Build 🏗️  ========"
if bun build; then
    echo "======== Build Completed Successfully ✅  ========"
    echo
    echo "Test ✅ Build ✅ Pushed 🚀"
else
    echo "❌ Build Failed"
    exit 1
fi
