name: Create diagram
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight

jobs:
  get_data:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github"
